name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        scala: ["2.12.12", "2.11.12"]
        spark: ["2.4.0", "3.0.0"]
        exclude:
          - scala: "2.11.12"
            spark: "3.0.0"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - name: Test
        run: sbt -Dspark.version=${{ matrix.spark  }} ++${{ matrix.scala }} test
